#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#homepage_shortcut:
#    path: /
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
#    defaults:
#        route: 'default'

#homepage:
#    path: /{_locale}
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#    requirements:
#        _locale: '%app_locales%'
#    defaults:
#        template: default/index.html.twig
#        _locale: '%locale%'

root:
    path: /
    controller: FrameworkBundle:Redirect:urlRedirect
    defaults:
        path: /%locale%
        permanent: true