# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
     locale: 'en'
     app_locales: en|de

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Domain,Base/Repository}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #doctrine.orm.custom_repository_factory:
    #    class: App\Base\RepositoryFactory\CustomRepositoryFactory
    #    #arguments:
        #    - '@app.another_command_handler_locator'

    #region CodeGenerator
    #https://symfony.com/doc/current/service_container/autowiring.html#working-with-interfaces
    #
    app.code.generator.default:
        class: App\Base\Services\CodeGeneratorDefault

    app.code.generator.hash:
        class: App\Base\Services\CodeGeneratorHash

    App\Base\Interfaces\CodeGeneratorInterface: '@app.code.generator.default'
    #endregion

    Aws\S3\S3Client:
        arguments:
            - version: '2006-03-01'
              region: '%env(AWS_DEFAULT_REGION)%'
              credentials:
                  key: '%env(AWS_ACCESS_KEY_ID)%'
                  secret: '%env(AWS_SECRET_ACCESS_KEY)%'

    #app.repository.factory:
    #    class: App\Base\RepositoryFactory\CustomRepositoryFactory
    #
    #App\Base\RepositoryFactory\CustomRepositoryFactory: '@app.repository.factory'